pagopa/selfcare-institution

- apps/institution-send-mail-scheduler/pom.xml
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/config/AzureStorageConfig.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/config/InstitutionSendMailConfig.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/entity/PecNotification.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/exception/GenericException.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/model/FileMailData.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/model/MailTemplate.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/repository/PecNotificationsRepository.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/MailService.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/MailServiceImpl.java
- apps/institution-send-mail-scheduler/src/main/resources/application.properties
- apps/institution-send-mail-scheduler/src/test/java/it/pagopa/selfcare/institution/service/MailServiceImplTest.java
- apps/institution-send-mail-scheduler/src/test/resources/application.properties
- infra/container_apps/institution-send-mail-scheduler/env/dev/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/prod/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/uat/terraform.tfvars
- Added sendMail method and configuration
We need to add method and env for send mail with users list
> [SELC-5163] Feat: Added sendMail method and configuration

- README.md
- apps/institution-send-mail-scheduler/Dockerfile
- apps/institution-send-mail-scheduler/pom.xml
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/Application.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/client/auth/AuthenticationPropagationHeadersFactory.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/config/AzureStorageConfig.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/config/InstitutionSendMailConfig.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/entity/PecNotification.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/repository/PecNotificationsRepository.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/InstitutionSendMailScheduledService.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/InstitutionSendMailScheduledServiceImpl.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/MailService.java
- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/MailServiceImpl.java
- apps/institution-send-mail-scheduler/src/main/openapi/selfcare-user.json
- apps/institution-send-mail-scheduler/src/main/resources/application.properties
- apps/institution-send-mail-scheduler/src/test/java/it/pagopa/selfcare/institution/ApplicationTest.java
- apps/institution-send-mail-scheduler/src/test/java/it/pagopa/selfcare/institution/service/InstitutionSendMailScheduledServiceImplTest.java
- apps/institution-send-mail-scheduler/src/test/java/it/pagopa/selfcare/institution/service/MailServiceImplTest.java
- docker-compose.yml
- infra/container_apps/institution-send-mail-scheduler/env/dev/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/prod/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/uat/terraform.tfvars
Added quarkus main class to send mail to institution
We need to schedule action to retrieve institution from PecNotification collection to send pec notification for user's list check
> [SELC-5166] Feat: Added quarkus main class to send mail to check user

- infra/container_apps/institution-send-mail-scheduler/.terraform.lock.hcl
- infra/container_apps/institution-send-mail-scheduler/data.tf
- infra/container_apps/institution-send-mail-scheduler/env/dev/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/prod/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/uat/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/locals.tf
- infra/container_apps/institution-send-mail-scheduler/main.tf
- infra/container_apps/institution-send-mail-scheduler/mongo_db.tf
- infra/repository/README.md
- Use azurerm_container_app_job to execute institution-send-mail-scheduler as Container App Job
- Upgrade terraform module mongodb collection
> [SELC-5167] feat: Added infra and schedulation to institution-send-mail-scheduler

- infra/container_apps/institution-send-mail-scheduler/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- test-coverage/pom.xml
> chore: Added test-coverage institution-send-mail

- .github/workflows/release_institution_ms.yml
- .github/workflows/release_institution_ms_pnpg.yml
- apps/institution-send-mail-scheduler/Dockerfile
> Fix: Docker remove WORKDIR src

- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/exception/CustomExceptionHandler.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/exception/CustomExceptionHandlerTest.java
- added custom exception handler for ValidationException to set errors status to 400
- added unit test
This change is required to handle ValidationException and avoid to throw unwanted 500
It was tested by running ms-institution locally and invoking GET /institutions API.
> [SELC-5267] bugfix: add custom exception handler for ValidationException

- apps/institution-ms/app/src/main/resources/config/core-config.properties
> fix property name in core-config.properties

- infra/container_apps/institution-send-mail-scheduler/env/prod/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/main.tf
- infra/container_apps/institution-send-mail-scheduler/variables.tf
* Added variable trigger_config to set trigger conditionally
* set manual trigger config for dev and uat
job on DEV and UAT must not be scheduled every day
> feat: Added manual trigger config for dev and uat

- apps/institution-send-mail-scheduler/src/main/java/it/pagopa/selfcare/institution/service/InstitutionSendMailScheduledServiceImpl.java
- apps/institution-send-mail-scheduler/src/test/java/it/pagopa/selfcare/institution/service/InstitutionSendMailScheduledServiceImplTest.java
Added a condition to check if dayDifference equals 0 and, if so, skip sending the email.
A new control has been added to handle cases where the dayDifference is equal to 0. When this condition is met, no email will be sent. This prevents unnecessary PECs from being sent when the difference in days is 0.
> fix: Disable Send Mail when Onboarding happen today

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyInfocamere.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionFromIpaPost.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- remove Conflict exception if institution already exists
- add supportEmail and supportPhone fields in request
- update supportEmail and suppportPhone fields
- align openapi
It was tested by running locally ms-institution and invoking createInstitutionFromIpa API
> [SELC-5306] feat: add supportEmail and supportPhone in createInstitutionFromIpa and update institution if it already exists

- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIvass.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- add supportPhone and supportEmail in createInstitutionFromIvass
- update institution if it's already present
It was tested by running ms-institution locally and invoking createInstitutionFromIvass API
> [SELC-5308] feat: add contacts to createInstitutionFromIvass and update Institution if it already exists

- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRaw.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- add supportPhone and supportEmail setting during createInstitution
- update institution if it already exists
- remove unused method checkIfAlreadyExistsByOriginAndOriginId
It was tested by running ms-institution locally and calling createInstitutionAPI
> [SELC-5318] feat: add contacts to CreateInstitutionRaw and update institution if it already exists

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java
This endpoint must be exposed by Internal API
> chore: Add tag internal-v1 on /delegations

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java
This endpoint must be exposed by Internal API
> chore: Add tag internal-v1 on /delegations/from-taxcode

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/app/src/main/resources/config/core-config.properties
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/config/CoreConfig.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionResourceMapper.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- infra/container_apps/institution-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/dev/terraform.tfvars
- infra/container_apps/institution-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/prod/terraform.tfvars
- infra/container_apps/institution-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/uat/terraform.tfvars
- add logo field in InstitutionResponse to retrieveInstitutionById API
- align openapi
> [SELC-5413] feat: add logo field in InstitutionResponse

- apps/institution-ms/connector-api/pom.xml
- apps/institution-send-mail-scheduler/pom.xml
Increase sdk product version 0.2.0
> [SELC-5520] feat: increase sdk product version to handle institutionContractMapping issue

- .github/workflows/create_release_branch.yml
> chore: Add Triggers to release ms and scheduler on Create-Release

- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
Catch DuplicateKey error of spring.dao and retry to save object with a different UUID
This PR fix an issue about an duplication key error when the service try to save an pnpg institution.The chance of generating two identical UUIDs is astronomically small but sometimes happens, we catch this error in order to retry saving object with a different UUID
> [SELC-5602] fix: catch Duplicate key error and retry to save object with different UUID

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
Change createdAt path with created-at
We are introducing an API standard which establish that endpoint must follow the param-case convention
> [SELC-5622] refactor: Change endpoint /createdAt in order to follow param-case standard

- apps/institution-ms/connector/rest/docs/openapi/registry_proxy.json
Updated registry_proxy.json
The path of the _searchByOriginIdUsingGET api has been updated, so it was necessary to adjust the openapi
local env
> [SELC-5755] fix: Updated registry_proxy.json

- apps/institution-migration/delete_pecNotification_PT.py
- apps/institution-migration/query.py
- Added script to delete pecNotification entity for institution with institutionType = PT
For institutions with institutionType = PT, the PEC notification entity must be removed
> [SELC-5702] Added script to delete pecNotification entity for institution with institutionType = PT

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/delegation/DelegationRequest.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/DelegationControllerTest.java
Added institutionFromRootName in createDelegation request
We need to persist this information for "Enti gestisti" section of dashboard FE
> [SELC-5866] Feat: Added institutionFromRootName in createDelegation request

- apps/institution-ms/pom.xml
org.bouncycastle:bcprov-jdk15on is affected by a lot of CVEs (CVSSv3.1:5,9)
> [SELC-5947] chore: upgrade version of org.bouncycastle to 1.78 to resolve CVEs

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/api/InstitutionConnector.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyAnac.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyInfocamere.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIvass.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRaw.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPdaTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRawTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- add product filter in getInstitutions API
This update ensures that the externally exposed API supports filtering based on the product associated with the subscription used in the request.
It was tested locally by testing all scenerios ensuring no regression.
> [SELC-6073] feat: add product filter in getInstitutions API

- README.md
Description about how setup github credentials and Prerequisites to run java microservice
> docs: added Prerequisites and GH Credentials to README

- infra/container_apps/institution-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/uat/terraform.tfvars
> [SELC-6134] Adding new scale rule for UAT

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/model/delegation/Delegation.java
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/mapper/DelegationInstitutionMapper.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImplTest.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImplTest.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionRepositoryTest.java
- apps/institution-ms/connector/dao/src/test/java/it/pagopa/selfcare/mscore/connector/dao/utils/TestUtils.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyIpa.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyPda.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/DelegationServiceImplTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/TestUtils.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java
- apps/institution-ms/pom.xml
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionFromIpaPost.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/mapper/InstitutionMapperCustom.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/TestUtils.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/ExternalControllerTest.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerPdaTest.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- set institutionType as a String instead of Enum
This change is required to avoid exception when different institutionTypes are added
> [SELC-6219] refactor: set institutionType as String instead of Enum

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector-api/pom.xml
- apps/institution-ms/connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/ProductConnectorImplTest.java
- apps/institution-ms/pom.xml
- update selfcare-commons version from 2.5.1 to 2.5.5
- update onboarding-sdk from 0.2.0 to 0.6.2
- update swagger with GPU InstitutionType
This change is required to manage new institutionType GPU
> [SELC-6225] feat: add GPU InstitutionType

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector/rest/docs/openapi/selfcare-user-docs.json
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/UserApiConnectorImpl.java
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/client/UserApiRestClient.java
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/client/UserInstitutionApiRestClient.java
- apps/institution-ms/connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/UserApiConnectorImplTest.java
- apps/institution-ms/pom.xml
- apps/institution-send-mail-scheduler/pom.xml
- upgrade commons version to 2.5.6 to add ADMIN_EA_IO
- upgrade sdk version to 0.6.8 to add ADMIN_EA_IO
- align openapis
> [SELC-6430] feat: add role ADMIN_EA_IO

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector/rest/docs/openapi/selfcare-user-docs.json
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/UserApiConnectorImpl.java
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/client/UserApiRestClient.java
- apps/institution-ms/connector/rest/src/main/java/it/pagopa/selfcare/mscore/connector/rest/client/UserInstitutionApiRestClient.java
- apps/institution-ms/connector/rest/src/test/java/it/pagopa/selfcare/mscore/connector/rest/UserApiConnectorImplTest.java
- apps/institution-ms/pom.xml
- apps/institution-send-mail-scheduler/pom.xml
Reverts pagopa/selfcare-institution#58
> Revert "[SELC-6430] feat: add role ADMIN_EA_IO"

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/api/InstitutionConnector.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/InstitutionConnectorImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionService.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImplTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/InstitutionController.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- Added subunits boolean parameter to getInstitutions endpoint in InstitutionController
- Updated related service methods
- Added findByTaxCodeWithSubunits method in InstitutionConnectorImpl
- Updated InstitutionControllerTest
- Updated InstitutionServiceImplTest
> [SELC-6117] Added subunits boolean parameter to getInstitutions endpoint

- apps/institution-mail-migration/README.md
- apps/institution-mail-migration/check_institutions_mail_notification.py
- apps/institution-mail-migration/check_mail_notification_institutions.py
- apps/institution-mail-migration/check_pec_notification_institutions.py
- apps/institution-mail-migration/pec_to_mail_notification.py
- Created script to check current PecNotification consistency with Institution collection
- Created script to migrate PecNotification documents to MailNotification
- Created script to check MailNotification consistency with Institution collection after the migration
To unify the user verification mail, we need to switch to the new MailNotification model. The python scripts automate the migration process and its control
- Local tests
> [SELC-6579] Added python scripts to migrate from PecNotification to MailNotification

- apps/delegation-cdc/pom.xml
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/DelegationCdcService.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/DelegationsEntity.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/Institution.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/OnboardingEntity.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/RelationshipState.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/filter/DelegationsFilter.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/entity/mapper/DelegationMapper.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/repository/DelegationRepository.java
- apps/delegation-cdc/src/main/java/it/pagopa/selfcare/delegation/event/repository/InstitutionRepository.java
- apps/delegation-cdc/src/main/resources/application.properties
- apps/delegation-cdc/src/test/java/it/pagopa/selfcare/delegation/event/repository/DelegationRepositoryTest.java
- apps/delegation-cdc/src/test/java/it/pagopa/selfcare/delegation/event/repository/InstitutionRepositoryTest.java
- apps/delegation-cdc/src/test/java/it/pagopa/selfcare/delegation/event/service/DelegationCdcServiceTest.java
- apps/delegation-cdc/src/test/resources/application.properties
- implement create PT delegations for aggregates
- add unit tests
It was tested locally
> [SELC-6601] feat: implement create delegation aggregates logic

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationV2Controller.java
- Rename /v2/v2/delegations in /v2/delegations/delegations-with-pagination
The external APIM already has a v2 in his name
- Local tests
> [SELC-7169] Renamed /v2/v2/delegations in /v2/delegations/delegations-with-pagination

- apps/institution-ms/app/pom.xml
- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/app/src/test/java/it/pagopa/selfcare/mscore/integration_test/steps/InstitutionSteps.java
- apps/institution-ms/app/src/test/resources/features/institution.feature
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Onboarding.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/inner/OnboardingEntity.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImpl.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/OnboardingServiceImplTest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/BulkProduct.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionOnboardingRequest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/OnboardingResponse.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/onboarding/OnboardedProductResponse.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- add InstitutionType origin and originId in InstitutionOnboardingRequest
- implement logic to set institutionType, origin and originId if not present in onboarding request
- replace commons-sdk InstitutionType with onboarding-sdk InstitutionType
- align cucumber tests
It was tested locally, by unit tests and cucumber tests
> [SELC-7112] feat: add InstitutionType origin and originId in InstitutionOnboardingRequest

- apps/institution-send-mail-scheduler/src/main/resources/application.properties
- apps/institution-send-mail-scheduler/src/test/resources/application.properties
- infra/container_apps/institution-ms/env/dev/terraform.tfvars
- infra/container_apps/institution-ms/env/prod/terraform.tfvars
- infra/container_apps/institution-ms/env/uat/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/dev/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/prod/terraform.tfvars
- infra/container_apps/institution-send-mail-scheduler/env/uat/terraform.tfvars
Contracts storage is deprecated by Documents storage. 
New key vault secrets update the Contracts env var.
> [SELC-7212] chore: Adding documents storage connections string and new container

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java
- added tag support in createDelegation
- added tag support  in openapi.json
Expose api createDelegation to the SM in order to use institution Id instead of taxCode
> [SELC-7296] feat: added tag support in createDelegation

- scripts/institution-types/check_delegation_types.py
- scripts/institution-types/update_delegation_types.py
- Added script to check delegations institutionToType and institutionFromType fields
- Added script to update delegations and align the institutionToType and institutionFromType with the respective institutionType under the onboarding node
The institutionType is also persisted inside the Delegations collection and it needs to match the one saved under the onboarding node of the institution / productId.
- Local tests
> [SELC-7152] Added scripts to check_delegation_types and update_delegation_types

- apps/institution-ms/app/src/main/resources/config/azure-storage-config.properties
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/config/AzureStorageConfig.java
- apps/institution-ms/connector/azure-storage/src/main/java/it/pagopa/selfcare/mscore/connector/azure_storage/AzureBlobClient.java
- apps/institution-ms/connector/azure-storage/src/test/java/it/pagopa/selfcare/mscore/connector/azure_storage/config/AzureStorageConfigTest.java
- infra/container_apps/institution-ms/env/dev-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/dev/terraform.tfvars
- infra/container_apps/institution-ms/env/prod-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/prod/terraform.tfvars
- infra/container_apps/institution-ms/env/uat-pnpg/terraform.tfvars
- infra/container_apps/institution-ms/env/uat/terraform.tfvars
- modify documents storage access
- modify SORAGE_CREDENTIAL_ID
- remove unused STORAGE_CREDENTIAL_SECRET and STORAGE_APPLICATION_SECRET
It was tested locally
> fix: modify documents storage access

- .gitignore
- scripts/delegation-add-dates/.env.example
- scripts/delegation-add-dates/README.md
- scripts/delegation-add-dates/check_valid_dates.py
- scripts/delegation-add-dates/delegation_add_createdAt.py
- scripts/institution-contract/.env.example
- scripts/institution-contract/README.md
- scripts/institution-contract/update_contract.py
-  python script to add createdAt field in delegation collection
It was tested locally
> [SELC-7385] feat: script to add createdAt in delegation

- apps/institution-ms/app/pom.xml
- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/app/src/test/resources/db/institution.json
- apps/institution-ms/app/src/test/resources/features/institution.feature
- apps/institution-ms/connector-api/src/main/java/it/pagopa/selfcare/mscore/model/institution/Institution.java
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/model/InstitutionEntity.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/InstitutionServiceImpl.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyCommon.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRaw.java
- apps/institution-ms/core/src/main/java/it/pagopa/selfcare/mscore/core/strategy/input/CreateInstitutionStrategyInput.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyRawTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/strategy/CreateInstitutionStrategyTest.java
- apps/institution-ms/core/src/test/java/it/pagopa/selfcare/mscore/core/util/TestUtils.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionRequest.java
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/model/institution/InstitutionResponse.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/TestUtils.java
- apps/institution-ms/web/src/test/java/it/pagopa/selfcare/mscore/web/controller/InstitutionControllerTest.java
- add legalForm in createInstitution request
- save legalForm field in InstiutitonEntity
- add legalForm in GETs responses
- upgrade cucumber sdk version
- align cucumber tests
Storing this information within the Institution is required to support "Multicanalità"/"Pari" teams.
Both locally and with cucumber tests
> [SELC-7404] feat: add legalForm in create institution request and responses

- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/web/src/main/java/it/pagopa/selfcare/mscore/web/controller/DelegationController.java
- add support tag in deleteDelegation API 
Allow support team to delete delegations by delegationId
> [SELC-7567] feat: add support tag in deleteDelegation API

- apps/institution-ms/app/src/test/resources/db/delegations.json
- apps/institution-ms/app/src/test/resources/features/institution.feature
- apps/institution-ms/connector/dao/src/main/java/it/pagopa/selfcare/mscore/connector/dao/DelegationConnectorImpl.java
- update field updatedAt in DelegationConnector
- update cucumber test
Ensure that the field updatedAt is updated as a result of changes made through the updateInstitution API.
Tested locally
> [SELC-7607] feat: update field updatedAt in DelegationConnector

- apps/delegation-cdc/pom.xml
- apps/institution-ms/app/src/main/docs/openapi.json
- apps/institution-ms/connector-api/pom.xml
- apps/institution-send-mail-scheduler/pom.xml
- update onboarding sdk version to add institution types SCEC and PRV_PF
This change is intended to handle the new institution types SCEC and PRV_PF
> [SELC-7757] feat: update onboarding sdk version to add institution types 
